### ISSUE TITLE
Use facial recognition to subtract fake reports portraying the same injured/dead people in one incident as people in another incident?

### ISSUE THREAD

**Issue by G-force78** [Gautamshahi/2023-Israel-Hamas-war#1]
Doing this may differentiate the propaganda from the authentic casualty reports

**Comment by Gautamshahi** [comment]
Sorry, I didn't get your point. Can you please elaborate on your point?

**Comment by G-force78** [comment]
I didnt really think it through, I was thinking how to eliminate propaganda from the vast amount of videos that are coming from the warzones so a clearer picture of the war is gained, howver it is unworkable for numerous reasons for one facial recognition inaccuracies and two the state of the casualty could well be so severe that the recognition just wouldnt recognbise a face. You can delete this thread. Thanks

**Comment by Gautamshahi** [comment]
okay, maybe something in the future can be done.
